//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace annorum_supra_18dec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_expense
    {
        public int id { get; set; }
        public string type { get; set; }
        public string subtype { get; set; }
        public string dscptn { get; set; }
        public System.DateTime date_purchased { get; set; }
        public decimal price { get; set; }
        public int quantity { get; set; }
    
        public virtual tbl_common_mtrl tbl_common_mtrl { get; set; }
    }
}
