//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace annorum_supra_18dec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_common_mtrl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_common_mtrl()
        {
            this.tbl_expense = new HashSet<tbl_expense>();
        }
    
        public int id { get; set; }
        public string type { get; set; }
        public string subtype { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_expense> tbl_expense { get; set; }
    }
}
